<?php
if(function_exists("register_field_group"))
{
    register_field_group(array (
        'id' => 'acf_author-social',
        'title' => 'Author Social',
        'fields' => array (
            array (
                'key' => 'field_54b37b7aed5aa',
                'label' => 'Facebook',
                'name' => 'facebook',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b37b8aed5ab',
                'label' => 'Twitter',
                'name' => 'twitter',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b37b92ed5ac',
                'label' => 'Google Plus',
                'name' => 'google_plus',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b37b9bed5ad',
                'label' => 'Pinterest',
                'name' => 'pinterest',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_user',
                    'operator' => '==',
                    'value' => 'all',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_blog-details',
        'title' => 'Blog Details',
        'fields' => array (
            array (
                'key' => 'field_54aa44af7cba9',
                'label' => 'Choose Your Blog Categories',
                'name' => 'choose_your_blog_categories',
                'type' => 'taxonomy',
                'instructions' => 'You can select your blog category to retrieve the posts.',
                'taxonomy' => 'category',
                'field_type' => 'select',
                'allow_null' => 0,
                'load_save_terms' => 0,
                'return_format' => 'id',
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54aa4aa47d47f',
                'label' => 'Number of posts to display',
                'name' => 'number_of_posts_to_display',
                'type' => 'number',
                'default_value' => 3,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 3,
                'max' => '',
                'step' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-blog.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_category-details',
        'title' => 'Category Details',
        'fields' => array (
            array (
                'key' => 'field_54b409e9642b2',
                'label' => 'Category Layout',
                'name' => 'category_layout',
                'type' => 'select',
                'instructions' => 'You can set your category page layout as full width or with sidebar.',
                'choices' => array (
                    'sidebar' => 'Sidebar',
                    'fullwidth' => 'Full Width',
                ),
                'default_value' => 'sidebar',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54b40413f8478',
                'label' => 'Hide Category Title',
                'name' => 'hide_category_title',
                'type' => 'true_false',
                'instructions' => 'You can hide complete category title area.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54b403dff8476',
                'label' => 'Category Sub Title',
                'name' => 'category_sub_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
			/*
            array (
                'key' => 'field_54b403f3f8477',
                'label' => 'Category Title Background',
                'name' => 'category_title_background',
                'type' => 'image',
                'save_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
            ),
			*/
        ),
        'location' => array (
            array (
                array (
                    'param' => 'ef_taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_home-page',
        'title' => 'Home Page',
        'fields' => array (
            array (
                'key' => 'field_549ea5fab2f5e',
                'label' => 'Choose Slider/Video/Color',
                'name' => 'choose_slider_video',
                'type' => 'select',
                'instructions' => 'You can either select the slider version or video version to display as home page.',
                'choices' => array (
                    'slider' => 'Slider',
                    'video' => 'Video',
                    'simple' => 'Color',
                ),
                'default_value' => 'slider',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_549ea6c8b2f5f',
                'label' => 'Slider Version',
                'name' => 'slider_version',
                'type' => 'repeater',
                'instructions' => 'Add unlimited slides as you want with caption & other details.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_549ea5fab2f5e',
                            'operator' => '==',
                            'value' => 'slider',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array (
                    array (
                        'key' => 'field_549ea756b2f60',
                        'label' => 'Slide Image',
                        'name' => 'slide_image',
                        'type' => 'image',
                        'column_width' => '',
                        'save_format' => 'url',
                        'preview_size' => 'full',
                        'library' => 'all',
                    ),
                    array (
                        'key' => 'field_549ea8b626e73',
                        'label' => 'Large Heading',
                        'name' => 'large_heading',
                        'type' => 'repeater',
                        'instructions' => 'Enter Your caption Heading, can be add twice per slide.',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_549ea9d4762fe',
                                'label' => 'Heading',
                                'name' => 'heading',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 2,
                        'layout' => 'table',
                        'button_label' => 'Add Heading',
                    ),
                    array (
                        'key' => 'field_549ea94026e74',
                        'label' => 'Small Text',
                        'name' => 'small_text',
                        'type' => 'repeater',
                        'instructions' => 'Enter Your caption small text, can be add twice per slide.',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_549ea9f8762ff',
                                'label' => 'Small Caption',
                                'name' => 'small_caption',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 2,
                        'layout' => 'table',
                        'button_label' => 'Add Small Caption',
                    ),
                    array (
                        'key' => 'field_549eab8a1d03c',
                        'label' => 'Button Text',
                        'name' => 'button_text',
                        'type' => 'text',
                        'instructions' => 'Leave empty if not required.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_549eb3288ac30',
                        'label' => 'Button Link',
                        'name' => 'button_link',
                        'type' => 'text',
                        'instructions' => 'Enter your Button link here.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => 1,
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Slides',
            ),
            array (
                'key' => 'field_549eb49ac740b',
                'label' => 'Upload Video',
                'name' => 'upload_video',
                'type' => 'file',
                'instructions' => 'Upload video in .mp4 format only.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_549ea5fab2f5e',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'library' => 'all',
            ),
            array (
                'key' => 'field_549eb45ac7403',
                'label' => 'Video Version',
                'name' => 'video_version',
                'type' => 'repeater',
                'instructions' => 'Add unlimited slides as you want with caption & other details.',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_549ea5fab2f5e',
                            'operator' => '==',
                            'value' => 'video',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'sub_fields' => array (
                    array (
                        'key' => 'field_549eb45ac7405',
                        'label' => 'Large Heading',
                        'name' => 'large_heading',
                        'type' => 'repeater',
                        'instructions' => 'Enter Your caption Heading, can be add twice per slide.',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_549eb45ac7406',
                                'label' => 'Heading',
                                'name' => 'heading',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 2,
                        'layout' => 'table',
                        'button_label' => 'Add Heading',
                    ),
                    array (
                        'key' => 'field_549eb45ac7407',
                        'label' => 'Small Text',
                        'name' => 'small_text',
                        'type' => 'repeater',
                        'instructions' => 'Enter Your caption small text, can be add twice per slide.',
                        'column_width' => '',
                        'sub_fields' => array (
                            array (
                                'key' => 'field_549eb45ac7408',
                                'label' => 'Small Caption',
                                'name' => 'small_caption',
                                'type' => 'text',
                                'column_width' => '',
                                'default_value' => '',
                                'placeholder' => '',
                                'prepend' => '',
                                'append' => '',
                                'formatting' => 'html',
                                'maxlength' => '',
                            ),
                        ),
                        'row_min' => 1,
                        'row_limit' => 2,
                        'layout' => 'table',
                        'button_label' => 'Add Small Caption',
                    ),
                    array (
                        'key' => 'field_549eb45ac7409',
                        'label' => 'Button Text',
                        'name' => 'button_text',
                        'type' => 'text',
                        'instructions' => 'Leave empty if not required.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                    array (
                        'key' => 'field_549eb45ac740a',
                        'label' => 'Button Link',
                        'name' => 'button_link',
                        'type' => 'text',
                        'instructions' => 'Enter your Button link here.',
                        'column_width' => '',
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'formatting' => 'html',
                        'maxlength' => '',
                    ),
                ),
                'row_min' => 1,
                'row_limit' => '',
                'layout' => 'row',
                'button_label' => 'Add Slides',
            ),
				array (
					'key' => 'field_549eb45ac7a05',
					'label' => 'Large Heading',
					'name' => 'large_heading',
					'type' => 'repeater',
					'instructions' => 'Enter Your caption Heading, can be add twice per slide.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_549ea5fab2f5e',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						'allorany' => 'all',
					),
					'column_width' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_549eb45ac7406',
							'label' => 'Heading',
							'name' => 'heading',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => 1,
					'row_limit' => 2,
					'layout' => 'table',
					'button_label' => 'Add Heading',
				),
				array (
					'key' => 'field_549eb45ac7a07',
					'label' => 'Small Text',
					'name' => 'small_text',
					'type' => 'repeater',
					'instructions' => 'Enter Your caption small text, can be add twice per slide.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_549ea5fab2f5e',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						'allorany' => 'all',
					),
					'column_width' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_549eb45ac7408',
							'label' => 'Small Caption',
							'name' => 'small_caption',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => 1,
					'row_limit' => 2,
					'layout' => 'table',
					'button_label' => 'Add Small Caption',
				),
				array (
					'key' => 'field_549eb45ac7a09',
					'label' => 'Button Text',
					'name' => 'button_text',
					'type' => 'text',
					'instructions' => 'Leave empty if not required.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_549ea5fab2f5e',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						'allorany' => 'all',
					),
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_549eb45ac7a0a',
					'label' => 'Button Link',
					'name' => 'button_link',
					'type' => 'text',
					'instructions' => 'Enter your Button link here.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_549ea5fab2f5e',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						'allorany' => 'all',
					),
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_549eb45ac7a8a',
					'label' => 'Background color',
					'name' => 'background',
					'type' => 'color_picker',
					'instructions' => '.',
					'conditional_logic' => array (
						'status' => 1,
						'rules' => array (
							array (
								'field' => 'field_549ea5fab2f5e',
								'operator' => '==',
								'value' => 'simple',
							),
						),
						'allorany' => 'all',
					),
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
		),
        'location' => array (
            array (
                array (
                    'param' => 'page_template',
                    'operator' => '==',
                    'value' => 'page-home.php',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
                0 => 'featured_image',
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_other-details',
        'title' => 'Other Details',
        'fields' => array (
            array (
                'key' => 'field_54aa59e1e7321',
                'label' => 'Page Sub Title',
                'name' => 'page_sub_title',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b6c8feda452',
                'label' => 'Hide Page Title',
                'name' => 'hide_page_title',
                'type' => 'true_false',
                'instructions' => 'You can hide your page title.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54b13262f7147',
                'label' => 'Page top padding',
                'name' => 'page_top_padding',
                'type' => 'number',
                'instructions' => 'Add your page padding from top.',
                'default_value' => 80,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_54b134306ef3a',
                'label' => 'Page bottom padding',
                'name' => 'page_bottom_padding',
                'type' => 'number',
                'instructions' => 'Add your page padding to bottom of the page.',
                'default_value' => 80,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_54b4231371359',
                'label' => 'Page Layout',
                'name' => 'page_layout',
                'type' => 'select',
                'instructions' => 'Set your page layout, this page layout will not effect the page section if use their. This will works only with default template of the page.',
                'choices' => array (
                    'fullwidth' => 'Fullwidth',
                    'sidebar' => 'Sidebar',
                ),
                'default_value' => 'fullwidth',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_portfolio-details',
        'title' => 'Portfolio Details',
        'fields' => array (
            array (
                'key' => 'field_54a39a56572d4',
                'label' => 'Portfolio Date',
                'name' => 'portfolio_date',
                'type' => 'date_picker',
                'date_format' => 'dd/mm/yy',
                'display_format' => 'dd.mm.yy',
                'first_day' => 1,
            ),
            array (
                'key' => 'field_54a39a8b572d5',
                'label' => 'Portfolio Client',
                'name' => 'portfolio_client',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54a3a07b852e2',
                'label' => 'Portfolio Item Size',
                'name' => 'portfolio_item_size',
                'type' => 'select',
                'instructions' => 'You can select either small or big size of the item.
	Small 25% by width.
	Big 50% by width.',
                'choices' => array (
                    'small' => 'Small',
                    'big' => 'Big',
                ),
                'default_value' => 'small',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54a39b30de0d8',
                'label' => 'Other Images',
                'name' => 'other_images',
                'type' => 'gallery',
                'preview_size' => 'full',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_post-details',
        'title' => 'Post Details',
        'fields' => array (
            array (
                'key' => 'field_54b3743df03dc',
                'label' => 'Show Title',
                'name' => 'show_title',
                'type' => 'true_false',
                'instructions' => 'All these changes will effects on single post view..',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54b3747bf03dd',
                'label' => 'Sub Title',
                'name' => 'sub_title',
                'type' => 'text',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_54b3743df03dc',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),

            array (
                'key' => 'field_54b4bf224d745',
                'label' => 'Post Layout',
                'name' => 'post_layout',
                'type' => 'select',
                'instructions' => 'You can set	your post layout as sidebar or fullwidth.',
                'choices' => array (
                    'sidebar' => 'Sidebar',
                    'fullwidth' => 'Fullwidth',
                ),
                'default_value' => 'sidebar',
                'allow_null' => 0,
                'multiple' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_section-details',
        'title' => 'Section Details',
        'fields' => array (
            array (
                'key' => 'field_54aa94ac21820',
                'label' => 'Select Page',
                'name' => 'select_page',
                'type' => 'post_object',
                'instructions' => 'Select page as your page section.',
                'post_type' => array (
                    0 => 'page',
                ),
                'taxonomy' => array (
                    0 => 'all',
                ),
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54b6cac3fca24',
                'label' => 'Hide Section Title',
                'name' => 'hide_section_title',
                'type' => 'true_false',
                'instructions' => 'You can hide your section title.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54aa93ff2181e',
                'label' => 'Enable Parallax Section',
                'name' => 'enable_parallax_section',
                'type' => 'true_false',
                'instructions' => 'You can enable/disable the section as parallax.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54aa94772181f',
                'label' => 'Parallax Image',
                'name' => 'parallax_image',
                'type' => 'image',
                'conditional_logic' => array (
                    'status' => 1,
                    'rules' => array (
                        array (
                            'field' => 'field_54aa93ff2181e',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                    'allorany' => 'all',
                ),
                'save_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54b1054250151',
                'label' => 'Section Top Padding',
                'name' => 'section_top_padding',
                'type' => 'number',
                'default_value' => 80,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_54b1056a50152',
                'label' => 'Section Bottom Padding',
                'name' => 'section_bottom_padding',
                'type' => 'number',
                'default_value' => 80,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => 0,
                'max' => '',
                'step' => '',
            ),
            array (
                'key' => 'field_54b2ae3aacbac',
                'label' => 'Section Full Width',
                'name' => 'section_full_width',
                'type' => 'true_false',
                'instructions' => 'This means you can set your section content outside the container, no more container width..!!',
                'message' => '',
                'default_value' => 0,
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'page-sections',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_team-details',
        'title' => 'Team Details',
        'fields' => array (
            array (
                'key' => 'field_54b114f32bdf3',
                'label' => 'Designation',
                'name' => 'designation',
                'type' => 'text',
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b115042bdf4',
                'label' => 'Member Image',
                'name' => 'member_image',
                'type' => 'image',
                'instructions' => 'Upload any image width equal dimensions e.g 500*500px',
                'save_format' => 'url',
                'preview_size' => 'full',
                'library' => 'all',
            ),
            array (
                'key' => 'field_54b115292bdf5',
                'label' => 'Facebook',
                'name' => 'facebook',
                'type' => 'text',
                'instructions' => 'Leave empty if not required.',
                'default_value' => '',
                'placeholder' => 'https://www.facebook.com',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b1157c2bdf7',
                'label' => 'Twitter',
                'name' => 'twitter',
                'type' => 'text',
                'instructions' => 'Leave empty if not required.',
                'default_value' => '',
                'placeholder' => 'http://www.twitter.com',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
            array (
                'key' => 'field_54b1157b2bdf6',
                'label' => 'Google Plus',
                'name' => 'google_plus',
                'type' => 'text',
                'instructions' => 'Leave empty if not required.',
                'default_value' => '',
                'placeholder' => 'http://..',
                'prepend' => '',
                'append' => '',
                'formatting' => 'html',
                'maxlength' => '',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'mikos-team',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 0,
    ));
    register_field_group(array (
        'id' => 'acf_animations-type',
        'title' => 'Animations Type',
        'fields' => array (
            array (
                'key' => 'field_54aa5448a9257',
                'label' => 'Disable Animation',
                'name' => 'disable_animation',
                'type' => 'true_false',
                'instructions' => 'You can enable & disable the animations.',
                'message' => '',
                'default_value' => 0,
            ),
            array (
                'key' => 'field_54aa5086abd7f',
                'label' => 'Select Animation Type',
                'name' => 'select_animation_type',
                'type' => 'select',
                'choices' => array (
                    'fadeIn' => 'FadeIn',
                    'fadeInDown' => 'FadeInDown',
                    'fadeInLeft' => 'FadeInLeft',
                    'fadeInRight' => 'FadeInRight',
                    'fadeInUp' => 'FadeInUp',
                    'zoomIn' => 'ZoomIn',
                    'zoomInDown' => 'ZoomInDown',
                    'zoomInLeft' => 'ZoomInLeft',
                    'zoomInRight' => 'ZoomInRight',
                    'zoomInUp' => 'ZoomInUp',
                    'zoomOut' => 'ZoomOut',
                ),
                'default_value' => 'fadeIn',
                'allow_null' => 0,
                'multiple' => 0,
            ),
            array (
                'key' => 'field_54aa5108dadcb',
                'label' => 'Animation Duration',
                'name' => 'animation_duration',
                'type' => 'number',
                'default_value' => 1,
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '0.1',
                'max' => 5,
                'step' => '0.1',
            ),
            array (
                'key' => 'field_54aa51dd4a060',
                'label' => 'Animation Delay',
                'name' => 'animation_delay',
                'type' => 'number',
                'default_value' => '0.4',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '0.1',
                'max' => 5,
                'step' => '0.1',
            ),
        ),
        'location' => array (
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'post',
                    'order_no' => 0,
                    'group_no' => 0,
                ),
            ),
            array (
                array (
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'portfolio',
                    'order_no' => 0,
                    'group_no' => 1,
                ),
            ),
        ),
        'options' => array (
            'position' => 'normal',
            'layout' => 'default',
            'hide_on_screen' => array (
            ),
        ),
        'menu_order' => 1,
    ));
}
